server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # сервер не регистрируется сам в себе
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0   # для быстрого запуска